// A map of prettier and more verbose names for Eris (Discord) permissions
// https://abal.moe/Eris/docs/reference

export default {
  createInstantInvite: 'Create Instant Invite',
  kickMembers: 'Kick Members',
  banMembers: 'Ban Members',
  administrator: 'Administrator',
  manageChannels: 'Manage Channels',
  manageGuild: 'Manage Guild',
  addReactions: 'Add Reactions',
  viewAuditLogs: 'View Audit Logs',
  voicePrioritySpeaker: 'Priority Speaker',
  stream: 'Video',
  readMessages: 'Read Messages',
  sendMessages: 'Send Messages',
  sendTTSMessages: 'Send TTS Messages',
  manageMessages: 'Manage Messages',
  embedLinks: 'Embed Links',
  attachFiles: 'Attach Files',
  readMessageHistory: 'Read Message History',
  mentionEveryone: 'Mention Everyone',
  externalEmojis: 'Use External Emojis',
  viewGuildInsights: 'View Guild Insights',
  voiceConnect: 'Connect',
  voiceSpeak: 'Speak',
  voiceMuteMembers: 'Mute Members',
  voiceDeafenMembers: 'Deafen Members',
  voiceMoveMembers: 'Move Members',
  voiceUseVAD: 'Use Voice Activity',
  changeNickname: 'Change Nickname',
  manageNicknames: 'Manage Nicknames',
  manageRoles: 'Manage Roles',
  manageWebhooks: 'Manage Guild',
  manageEmojis: 'Manage Emojis',
  all: 'All Permissions',
  allGuild: 'All Guild Permissions',
  allText: 'All Text Permissions',
  allVoice: 'All Voice Permissions'
}
